name: Keep Multiple Streamlit Apps Awake

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Requests to Keep Apps Awake
        run: |
          curl -s https://german-credit-risk-prediction.streamlit.app/
          curl -s https://trip-advisor-llm-by-suriyag.streamlit.app/
         
