name: Keep Multiple Streamlit Apps Awake

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Requests to Keep Apps Awake
        run: |
          curl -s https://app1-name.streamlit.app/
          curl -s https://app2-name.streamlit.app/
          curl -s https://app3-name.streamlit.app/
